// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package kv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// If values are added to this, be sure to update the config() function
type Configuration struct {
	MaxVersions          uint32             `protobuf:"varint,1,opt,name=max_versions,json=maxVersions,proto3" json:"max_versions,omitempty"`
	CasRequired          bool               `protobuf:"varint,2,opt,name=cas_required,json=casRequired,proto3" json:"cas_required,omitempty"`
	VersionTtl           *duration.Duration `protobuf:"bytes,3,opt,name=version_ttl,json=versionTtl,proto3" json:"version_ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Configuration) Reset()         { *m = Configuration{} }
func (m *Configuration) String() string { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()    {}
func (*Configuration) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Configuration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Configuration.Unmarshal(m, b)
}
func (m *Configuration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Configuration.Marshal(b, m, deterministic)
}
func (m *Configuration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Configuration.Merge(m, src)
}
func (m *Configuration) XXX_Size() int {
	return xxx_messageInfo_Configuration.Size(m)
}
func (m *Configuration) XXX_DiscardUnknown() {
	xxx_messageInfo_Configuration.DiscardUnknown(m)
}

var xxx_messageInfo_Configuration proto.InternalMessageInfo

func (m *Configuration) GetMaxVersions() uint32 {
	if m != nil {
		return m.MaxVersions
	}
	return 0
}

func (m *Configuration) GetCasRequired() bool {
	if m != nil {
		return m.CasRequired
	}
	return false
}

func (m *Configuration) GetVersionTtl() *duration.Duration {
	if m != nil {
		return m.VersionTtl
	}
	return nil
}

type VersionMetadata struct {
	// CreatedTime is when the version was created.
	CreatedTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// DeletionTime is the time this version becomes invalid.
	// Set to Now() to delete the version before the configured
	// delete time.
	DeletionTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=deletion_time,json=deletionTime,proto3" json:"deletion_time,omitempty"`
	// Destroyed is used to specify this version is
	// a has been removed and the underlying data deleted.
	Destroyed            bool     `protobuf:"varint,3,opt,name=destroyed,proto3" json:"destroyed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionMetadata) Reset()         { *m = VersionMetadata{} }
func (m *VersionMetadata) String() string { return proto.CompactTextString(m) }
func (*VersionMetadata) ProtoMessage()    {}
func (*VersionMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *VersionMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionMetadata.Unmarshal(m, b)
}
func (m *VersionMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionMetadata.Marshal(b, m, deterministic)
}
func (m *VersionMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionMetadata.Merge(m, src)
}
func (m *VersionMetadata) XXX_Size() int {
	return xxx_messageInfo_VersionMetadata.Size(m)
}
func (m *VersionMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_VersionMetadata proto.InternalMessageInfo

func (m *VersionMetadata) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *VersionMetadata) GetDeletionTime() *timestamp.Timestamp {
	if m != nil {
		return m.DeletionTime
	}
	return nil
}

func (m *VersionMetadata) GetDestroyed() bool {
	if m != nil {
		return m.Destroyed
	}
	return false
}

type KeyMetadata struct {
	// Key is the key for this entry
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Versions is the map of versionID -> VersionMetadata.
	// Useful when listing all versions.
	Versions map[uint64]*VersionMetadata `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// CurrentVersion is the latest version of the value
	CurrentVersion uint64 `protobuf:"varint,3,opt,name=current_version,json=currentVersion,proto3" json:"current_version,omitempty"`
	// OldestVersion is the oldest version of the value.
	OldestVersion uint64 `protobuf:"varint,4,opt,name=oldest_version,json=oldestVersion,proto3" json:"oldest_version,omitempty"`
	// Created time is when the metadata was created.
	CreatedTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// Updated time was the last time the metadata version
	// was updated.
	UpdatedTime *timestamp.Timestamp `protobuf:"bytes,6,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	// MaxVersions specifies how many versions to keep around.
	// If empty value, defaults to the configured Max
	// for the mount.
	MaxVersions uint32 `protobuf:"varint,7,opt,name=max_versions,json=maxVersions,proto3" json:"max_versions,omitempty"`
	// CasRequired specifies if the cas parameter is
	// required for this key
	CasRequired bool `protobuf:"varint,8,opt,name=cas_required,json=casRequired,proto3" json:"cas_required,omitempty"`
	// VersionTtl specifies how long to keep versions around. If empty
	// value, defaults to the configured version_ttl for the mount.
	VersionTtl           *duration.Duration `protobuf:"bytes,9,opt,name=version_ttl,json=versionTtl,proto3" json:"version_ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *KeyMetadata) Reset()         { *m = KeyMetadata{} }
func (m *KeyMetadata) String() string { return proto.CompactTextString(m) }
func (*KeyMetadata) ProtoMessage()    {}
func (*KeyMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *KeyMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyMetadata.Unmarshal(m, b)
}
func (m *KeyMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyMetadata.Marshal(b, m, deterministic)
}
func (m *KeyMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyMetadata.Merge(m, src)
}
func (m *KeyMetadata) XXX_Size() int {
	return xxx_messageInfo_KeyMetadata.Size(m)
}
func (m *KeyMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_KeyMetadata proto.InternalMessageInfo

func (m *KeyMetadata) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyMetadata) GetVersions() map[uint64]*VersionMetadata {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *KeyMetadata) GetCurrentVersion() uint64 {
	if m != nil {
		return m.CurrentVersion
	}
	return 0
}

func (m *KeyMetadata) GetOldestVersion() uint64 {
	if m != nil {
		return m.OldestVersion
	}
	return 0
}

func (m *KeyMetadata) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *KeyMetadata) GetUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

func (m *KeyMetadata) GetMaxVersions() uint32 {
	if m != nil {
		return m.MaxVersions
	}
	return 0
}

func (m *KeyMetadata) GetCasRequired() bool {
	if m != nil {
		return m.CasRequired
	}
	return false
}

func (m *KeyMetadata) GetVersionTtl() *duration.Duration {
	if m != nil {
		return m.VersionTtl
	}
	return nil
}

type Version struct {
	// Data is a JSON object with string keys that
	// represents the user supplied data.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// CreatedTime is when the version was created.
	CreatedTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	// DeletionTime is the time this version becomes invalid.
	// Set to Now() to delete the version before the configured
	// deletion time.
	DeletionTime         *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deletion_time,json=deletionTime,proto3" json:"deletion_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Version) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *Version) GetDeletionTime() *timestamp.Timestamp {
	if m != nil {
		return m.DeletionTime
	}
	return nil
}

type UpgradeInfo struct {
	// Started time is when the upgrade was started.
	StartedTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=started_time,json=startedTime,proto3" json:"started_time,omitempty"`
	// done is set to true once the backend has been successfully
	// upgraded.
	Done                 bool     `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeInfo) Reset()         { *m = UpgradeInfo{} }
func (m *UpgradeInfo) String() string { return proto.CompactTextString(m) }
func (*UpgradeInfo) ProtoMessage()    {}
func (*UpgradeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *UpgradeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeInfo.Unmarshal(m, b)
}
func (m *UpgradeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeInfo.Marshal(b, m, deterministic)
}
func (m *UpgradeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeInfo.Merge(m, src)
}
func (m *UpgradeInfo) XXX_Size() int {
	return xxx_messageInfo_UpgradeInfo.Size(m)
}
func (m *UpgradeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeInfo proto.InternalMessageInfo

func (m *UpgradeInfo) GetStartedTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartedTime
	}
	return nil
}

func (m *UpgradeInfo) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func init() {
	proto.RegisterType((*Configuration)(nil), "kv.Configuration")
	proto.RegisterType((*VersionMetadata)(nil), "kv.VersionMetadata")
	proto.RegisterType((*KeyMetadata)(nil), "kv.KeyMetadata")
	proto.RegisterMapType((map[uint64]*VersionMetadata)(nil), "kv.KeyMetadata.VersionsEntry")
	proto.RegisterType((*Version)(nil), "kv.Version")
	proto.RegisterType((*UpgradeInfo)(nil), "kv.UpgradeInfo")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0x3e, 0x76, 0xb7, 0x1d, 0x27, 0xbb, 0xc8, 0x5c, 0x4a, 0xc5, 0x47, 0x89, 0x84, 0x28,
	0x97, 0xac, 0x54, 0x2e, 0xb0, 0xd2, 0x8a, 0x03, 0x70, 0x40, 0x08, 0x09, 0x59, 0x0b, 0xd7, 0xe2,
	0xad, 0xa7, 0x55, 0xd4, 0x34, 0x0e, 0x8e, 0x53, 0x6d, 0x7e, 0x06, 0x3f, 0x80, 0xdf, 0xc0, 0x1f,
	0xe4, 0x80, 0xec, 0x38, 0xdd, 0x52, 0x90, 0xaa, 0x6a, 0x6f, 0xd6, 0xf3, 0x7b, 0xe3, 0x37, 0x33,
	0xcf, 0x40, 0x74, 0x53, 0x62, 0x95, 0x96, 0x4a, 0x6a, 0x49, 0xfd, 0xe5, 0x7a, 0xf8, 0x64, 0x21,
	0xe5, 0x22, 0xc7, 0x73, 0x8b, 0x5c, 0xd7, 0xf3, 0x73, 0x9d, 0xad, 0xb0, 0xd2, 0x7c, 0x55, 0xb6,
	0xa4, 0xe1, 0xe3, 0x5d, 0x82, 0xa8, 0x15, 0xd7, 0x99, 0x2c, 0xda, 0xfb, 0xe4, 0x87, 0x07, 0xf1,
	0x5b, 0x59, 0xcc, 0xb3, 0x85, 0xc3, 0xe9, 0x53, 0x88, 0x56, 0xfc, 0x66, 0xba, 0x46, 0x55, 0x65,
	0xb2, 0xa8, 0x06, 0xde, 0xc8, 0x1b, 0xc7, 0x8c, 0xac, 0xf8, 0xcd, 0x57, 0x07, 0x19, 0xca, 0x8c,
	0x57, 0x53, 0x85, 0xdf, 0xeb, 0x4c, 0xa1, 0x18, 0xf8, 0x23, 0x6f, 0xdc, 0x63, 0x64, 0xc6, 0x2b,
	0xe6, 0x20, 0x7a, 0x01, 0xc4, 0x55, 0x98, 0x6a, 0x9d, 0x0f, 0x82, 0x91, 0x37, 0x26, 0x93, 0x07,
	0x69, 0xeb, 0x26, 0xed, 0xdc, 0xa4, 0xef, 0xdc, 0xab, 0x0c, 0x1c, 0xfb, 0x4a, 0xe7, 0xc9, 0x2f,
	0x0f, 0xce, 0xdc, 0x5b, 0x9f, 0x50, 0x73, 0xc1, 0x35, 0xa7, 0x97, 0x10, 0xcd, 0x14, 0x72, 0x8d,
	0x62, 0x6a, 0x5a, 0xb4, 0xae, 0xc8, 0x64, 0xf8, 0x4f, 0xc1, 0xab, 0xae, 0x7f, 0x46, 0x1c, 0xdf,
	0x20, 0xf4, 0x0d, 0xc4, 0x02, 0x73, 0xd4, 0xd6, 0x8f, 0xd1, 0xfb, 0x7b, 0xf5, 0x51, 0x27, 0xb0,
	0x05, 0x1e, 0x42, 0x5f, 0x60, 0xa5, 0x95, 0x6c, 0x50, 0xd8, 0x6e, 0x7a, 0xec, 0x16, 0x48, 0x7e,
	0x07, 0x40, 0x3e, 0x62, 0xb3, 0x71, 0x7b, 0x0f, 0x82, 0x25, 0x36, 0xd6, 0x64, 0x9f, 0x99, 0x23,
	0x7d, 0x0d, 0xbd, 0xcd, 0x44, 0xfd, 0x51, 0x30, 0x26, 0x93, 0x47, 0xe9, 0x72, 0x9d, 0x6e, 0x89,
	0xd2, 0x6e, 0xbc, 0xef, 0x0b, 0xad, 0x1a, 0xb6, 0xa1, 0xd3, 0xe7, 0x70, 0x36, 0xab, 0x95, 0xc2,
	0x42, 0x77, 0x4b, 0xb1, 0x06, 0x42, 0x76, 0xea, 0x60, 0x27, 0xa4, 0xcf, 0xe0, 0x54, 0xe6, 0xc6,
	0xd4, 0x86, 0x17, 0x5a, 0x5e, 0xdc, 0xa2, 0x1d, 0x6d, 0x77, 0x94, 0x47, 0x87, 0x8d, 0xf2, 0x12,
	0xa2, 0xba, 0x14, 0xb7, 0xf2, 0xe3, 0xfd, 0x72, 0xc7, 0xb7, 0xf2, 0xdd, 0x78, 0x9d, 0xec, 0x8f,
	0x57, 0x6f, 0x6f, 0xbc, 0xfa, 0x07, 0xc4, 0x6b, 0xf8, 0x19, 0xe2, 0xbf, 0x46, 0xbd, 0xbd, 0xad,
	0xb0, 0xdd, 0xd6, 0x0b, 0x38, 0x5a, 0xf3, 0xbc, 0xee, 0x62, 0x72, 0xdf, 0xac, 0x6a, 0x27, 0x91,
	0xac, 0x65, 0x5c, 0xf8, 0xaf, 0xbc, 0xe4, 0xa7, 0x07, 0x27, 0xdd, 0x74, 0x29, 0x84, 0xe6, 0xda,
	0x56, 0x8b, 0x58, 0xf8, 0xdf, 0xf0, 0xfa, 0x77, 0x0c, 0x6f, 0x70, 0x58, 0x78, 0x93, 0x6f, 0x40,
	0xbe, 0x94, 0x0b, 0xc5, 0x05, 0x7e, 0x28, 0xe6, 0xd2, 0xd8, 0xa9, 0x34, 0x57, 0x87, 0xfc, 0x25,
	0xc7, 0xb7, 0x76, 0x4c, 0x87, 0xb2, 0x40, 0xf7, 0xeb, 0xed, 0xf9, 0xfa, 0xd8, 0x8a, 0x5e, 0xfe,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xa8, 0x35, 0xd4, 0xa1, 0x04, 0x00, 0x00,
}
