// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package vkv is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Configuration
	VersionMetadata
	KeyMetadata
	Version
	UpgradeInfo
*/
package vkv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Configuration struct {
	MaxVersions uint32 `protobuf:"varint,1,opt,name=max_versions,json=maxVersions" json:"max_versions,omitempty"`
	CasRequired bool   `protobuf:"varint,2,opt,name=cas_required,json=casRequired" json:"cas_required,omitempty"`
}

func (m *Configuration) Reset()                    { *m = Configuration{} }
func (m *Configuration) String() string            { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()               {}
func (*Configuration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Configuration) GetMaxVersions() uint32 {
	if m != nil {
		return m.MaxVersions
	}
	return 0
}

func (m *Configuration) GetCasRequired() bool {
	if m != nil {
		return m.CasRequired
	}
	return false
}

type VersionMetadata struct {
	// CreatedTime is when the version was created.
	CreatedTime *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	// DeletionTime is the time this version becomes invalid.
	// Set to Now() to delete the version before the configured
	// delete time.
	DeletionTime *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=deletion_time,json=deletionTime" json:"deletion_time,omitempty"`
	// Destroyed is used to specify this version is
	// a has been removed and the underlying data deleted.
	Destroyed bool `protobuf:"varint,3,opt,name=destroyed" json:"destroyed,omitempty"`
}

func (m *VersionMetadata) Reset()                    { *m = VersionMetadata{} }
func (m *VersionMetadata) String() string            { return proto.CompactTextString(m) }
func (*VersionMetadata) ProtoMessage()               {}
func (*VersionMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VersionMetadata) GetCreatedTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *VersionMetadata) GetDeletionTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.DeletionTime
	}
	return nil
}

func (m *VersionMetadata) GetDestroyed() bool {
	if m != nil {
		return m.Destroyed
	}
	return false
}

type KeyMetadata struct {
	// Key is the key for this entry
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// Versions is the map of versionID -> VersionMetadata.
	// Useful when listing all versions.
	Versions map[uint64]*VersionMetadata `protobuf:"bytes,2,rep,name=versions" json:"versions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// CurrentVersion is the latest version of the value
	CurrentVersion uint64 `protobuf:"varint,3,opt,name=current_version,json=currentVersion" json:"current_version,omitempty"`
	// OldestVersion is the oldest version of the value.
	OldestVersion uint64 `protobuf:"varint,4,opt,name=oldest_version,json=oldestVersion" json:"oldest_version,omitempty"`
	// Created time is when the metadata was created.
	CreatedTime *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	// Updated time was the last time the metadata version
	// was updated.
	UpdatedTime *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=updated_time,json=updatedTime" json:"updated_time,omitempty"`
	// MaxVersions specifies how many versions to keep around.
	// If empty value, defaults to the configured Max
	// for the mount.
	MaxVersions uint32 `protobuf:"varint,7,opt,name=max_versions,json=maxVersions" json:"max_versions,omitempty"`
	// CasRequired specifies if the cas parameter is
	// required for this key
	CasRequired bool `protobuf:"varint,8,opt,name=cas_required,json=casRequired" json:"cas_required,omitempty"`
}

func (m *KeyMetadata) Reset()                    { *m = KeyMetadata{} }
func (m *KeyMetadata) String() string            { return proto.CompactTextString(m) }
func (*KeyMetadata) ProtoMessage()               {}
func (*KeyMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *KeyMetadata) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyMetadata) GetVersions() map[uint64]*VersionMetadata {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *KeyMetadata) GetCurrentVersion() uint64 {
	if m != nil {
		return m.CurrentVersion
	}
	return 0
}

func (m *KeyMetadata) GetOldestVersion() uint64 {
	if m != nil {
		return m.OldestVersion
	}
	return 0
}

func (m *KeyMetadata) GetCreatedTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *KeyMetadata) GetUpdatedTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

func (m *KeyMetadata) GetMaxVersions() uint32 {
	if m != nil {
		return m.MaxVersions
	}
	return 0
}

func (m *KeyMetadata) GetCasRequired() bool {
	if m != nil {
		return m.CasRequired
	}
	return false
}

type Version struct {
	// Data is a JSON object with string keys that
	// represents the user supplied data.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// CreatedTime is when the version was created.
	CreatedTime *google_protobuf.Timestamp `protobuf:"bytes,2,opt,name=created_time,json=createdTime" json:"created_time,omitempty"`
	// DeletionTime is the time this version becomes invalid.
	// Set to Now() to delete the version before the configured
	// deletion time.
	DeletionTime *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=deletion_time,json=deletionTime" json:"deletion_time,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Version) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Version) GetCreatedTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *Version) GetDeletionTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.DeletionTime
	}
	return nil
}

type UpgradeInfo struct {
	// Started time is when the upgrade was started.
	StartedTime *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=started_time,json=startedTime" json:"started_time,omitempty"`
}

func (m *UpgradeInfo) Reset()                    { *m = UpgradeInfo{} }
func (m *UpgradeInfo) String() string            { return proto.CompactTextString(m) }
func (*UpgradeInfo) ProtoMessage()               {}
func (*UpgradeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpgradeInfo) GetStartedTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartedTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Configuration)(nil), "vkv.Configuration")
	proto.RegisterType((*VersionMetadata)(nil), "vkv.VersionMetadata")
	proto.RegisterType((*KeyMetadata)(nil), "vkv.KeyMetadata")
	proto.RegisterType((*Version)(nil), "vkv.Version")
	proto.RegisterType((*UpgradeInfo)(nil), "vkv.UpgradeInfo")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xdf, 0x6a, 0xd4, 0x40,
	0x18, 0xc5, 0xc9, 0x9f, 0xb6, 0xdb, 0x2f, 0x49, 0x2b, 0x83, 0x17, 0xcb, 0x22, 0xba, 0x06, 0xc4,
	0xc5, 0x8b, 0x14, 0xea, 0x8d, 0x14, 0x8a, 0x17, 0xe2, 0x85, 0xa8, 0x17, 0x0e, 0xd6, 0xdb, 0x65,
	0xba, 0xf3, 0xed, 0x12, 0x76, 0x37, 0x13, 0x67, 0x26, 0xa1, 0x79, 0x18, 0x9f, 0xc1, 0x77, 0xf0,
	0xc9, 0x64, 0x26, 0x33, 0x69, 0x5d, 0x85, 0x65, 0xf1, 0x2e, 0x9c, 0xfc, 0xce, 0xc7, 0xe1, 0xe4,
	0x04, 0x12, 0xdd, 0xd5, 0xa8, 0x8a, 0x5a, 0x0a, 0x2d, 0x48, 0xd4, 0xae, 0xdb, 0xc9, 0xb3, 0x95,
	0x10, 0xab, 0x0d, 0x5e, 0x58, 0xe9, 0xb6, 0x59, 0x5e, 0xe8, 0x72, 0x8b, 0x4a, 0xb3, 0x6d, 0xdd,
	0x53, 0xf9, 0x0d, 0x64, 0xef, 0x44, 0xb5, 0x2c, 0x57, 0x8d, 0x64, 0xba, 0x14, 0x15, 0x79, 0x0e,
	0xe9, 0x96, 0xdd, 0xcd, 0x5b, 0x94, 0xaa, 0x14, 0x95, 0x1a, 0x07, 0xd3, 0x60, 0x96, 0xd1, 0x64,
	0xcb, 0xee, 0xbe, 0x39, 0xc9, 0x20, 0x0b, 0xa6, 0xe6, 0x12, 0xbf, 0x37, 0xa5, 0x44, 0x3e, 0x0e,
	0xa7, 0xc1, 0x6c, 0x44, 0x93, 0x05, 0x53, 0xd4, 0x49, 0xf9, 0xcf, 0x00, 0xce, 0x1d, 0xff, 0x19,
	0x35, 0xe3, 0x4c, 0x33, 0x72, 0x0d, 0xe9, 0x42, 0x22, 0xd3, 0xc8, 0xe7, 0x26, 0x85, 0xbd, 0x9c,
	0x5c, 0x4e, 0x8a, 0x3e, 0x62, 0xe1, 0x23, 0x16, 0x5f, 0x7d, 0x44, 0x9a, 0x38, 0xde, 0x28, 0xe4,
	0x2d, 0x64, 0x1c, 0x37, 0x68, 0x42, 0xf6, 0xfe, 0x70, 0xaf, 0x3f, 0xf5, 0x06, 0x7b, 0xe0, 0x09,
	0x9c, 0x72, 0x54, 0x5a, 0x8a, 0x0e, 0xf9, 0x38, 0xb2, 0x99, 0xef, 0x85, 0xfc, 0x57, 0x04, 0xc9,
	0x47, 0xec, 0x86, 0xb4, 0x8f, 0x20, 0x5a, 0x63, 0x67, 0x43, 0x9e, 0x52, 0xf3, 0x48, 0xae, 0x60,
	0x34, 0xb4, 0x12, 0x4e, 0xa3, 0x59, 0x72, 0xf9, 0xb4, 0x68, 0xd7, 0x6d, 0xf1, 0xc0, 0x55, 0xf8,
	0x8e, 0xde, 0x57, 0x5a, 0x76, 0x74, 0xe0, 0xc9, 0x4b, 0x38, 0x5f, 0x34, 0x52, 0x62, 0xa5, 0x7d,
	0xb3, 0x36, 0x41, 0x4c, 0xcf, 0x9c, 0xec, 0x8c, 0xe4, 0x05, 0x9c, 0x89, 0x8d, 0x49, 0x35, 0x70,
	0xb1, 0xe5, 0xb2, 0x5e, 0xf5, 0xd8, 0x6e, 0x97, 0x47, 0x87, 0x75, 0x79, 0x0d, 0x69, 0x53, 0xf3,
	0x7b, 0xfb, 0xf1, 0x7e, 0xbb, 0xe3, 0xad, 0x7d, 0x77, 0x23, 0x27, 0xfb, 0x37, 0x32, 0xfa, 0x6b,
	0x23, 0x93, 0x2f, 0x90, 0xfd, 0x51, 0xd7, 0xc3, 0xca, 0xe3, 0xbe, 0xf2, 0x57, 0x70, 0xd4, 0xb2,
	0x4d, 0xe3, 0xbf, 0xf5, 0x63, 0xdb, 0xf7, 0xce, 0xae, 0x68, 0x8f, 0x5c, 0x85, 0x6f, 0x82, 0xfc,
	0x47, 0x00, 0x27, 0xbe, 0x22, 0x02, 0xb1, 0x79, 0x6d, 0xcf, 0xa5, 0x34, 0xfe, 0xe7, 0x04, 0xc3,
	0xff, 0x9c, 0x60, 0x74, 0xd8, 0x04, 0xf3, 0x4f, 0x90, 0xdc, 0xd4, 0x2b, 0xc9, 0x38, 0x7e, 0xa8,
	0x96, 0xc2, 0xc4, 0x51, 0x9a, 0xc9, 0x43, 0xfe, 0x08, 0xc7, 0x1b, 0xe5, 0xf6, 0xd8, 0x02, 0xaf,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xb4, 0xb1, 0x57, 0xf7, 0x03, 0x00, 0x00,
}
