version: 2.1

references:
  images:
    go: &GOLANG_IMAGE docker.mirror.hashicorp.services/cimg/go:1.17.2 

jobs:
  go-test:
    docker:
      - image: *GOLANG_IMAGE
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/hashicorp/vault-plugin-secrets-kv
    steps:
      - checkout
      - run: go test
        
workflows:
  tests:
    jobs:
      - go-test
