name: Linting workflows

on:
  push:
    paths:
      - .github/**

permissions:
  contents: none

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: "Check GitHub workflow files"
        uses: docker://docker.mirror.hashicorp.services/rhysd/actionlint:latest
        with:
          args: -color
