name: tests
on:
  push:
permissions:
  contents: none
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: .go-version
          check-latest: true
      - name: go test
        env:
          GO111MODULE: 'on'
        run: go test
